debugging workflow
Signed-off-by: Maroun Touma <touma@us.ibm.com>

diff --git a/.github/workflows/test-universal-opensearch.yml b/.github/workflows/test-universal-opensearch.yml
--- a/.github/workflows/test-universal-opensearch.yml
+++ b/.github/workflows/test-universal-opensearch.yml
@@ -71,9 +71,8 @@ jobs:
                   echo "publish_images=$publish_images" >> "$GITHUB_OUTPUT"
     test-src:
         runs-on: ubuntu-22.04
-        env:
+#        env:
 #            OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${{ secrets.OPENSEARCH_INITIAL_ADMIN_PASSWORD }}
-            OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${RANDOM}$(date +%s)
         steps:
             - name: Checkout
               uses: actions/checkout@v4
@@ -89,15 +88,20 @@ jobs:
             - name: Setup opensearch local instance
               # Setup a local instance of opensearch container
               run: |
-                  echo OPENSEARCH_INITIAL_ADMIN_PASSWORD = $OPENSEARCH_INITIAL_ADMIN_PASSWORD
+                  export OPENSEARCH_INITIAL_ADMIN_PASSWORD=${RANDOM}$(date +%s)
+                  echo OPENSEARCH_INITIAL_ADMIN_PASSWORD = ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
                   git clone https://github.com/opensearch-project/opensearch-build.git
-                  ls -l
                   cd opensearch-build/docker/release/dockercomposefiles/
                   docker compose -f docker-compose-default.x.yml up -d
             - name: Test transform source in transforms/universal/opensearch
               run: |
                   if [ -e "transforms/universal/opensearch/Makefile" ]; then
-                      export OPENSEARCH_PASSWORD=$OPENSEARCH_INITIAL_ADMIN_PASSWORD
+                      export OPENSEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
+                      echo OPENSEARCH_PASSWORD = ${OPENSEARCH_PASSWORD}
+                      if [ -z "${OPENSEARCH_PASSWORD}" ]; then
+                          echo "OPENSEARCH_PASSWORD environment variable not set - cannot run tests against OpenSearch"
+                          exit 1
+                      fi
                       make -C transforms/universal/opensearch DOCKER=docker test-src
                   else
                       echo "transforms/universal/opensearch/Makefile not found - source testing disabled for this transform."
