verify permission before checkout
Signed-off-by: Maroun Touma <touma@us.ibm.com>

diff --git a/.github/workflows/test-language-gneissweb_classification.yml b/.github/workflows/test-language-gneissweb_classification.yml
--- a/.github/workflows/test-language-gneissweb_classification.yml
+++ b/.github/workflows/test-language-gneissweb_classification.yml
@@ -69,19 +69,42 @@ jobs:
                     publish_images='true'
                   fi
                   echo "publish_images=$publish_images" >> "$GITHUB_OUTPUT"
+
+    check_if_allowed:
+        runs-on: ubuntu-22.04
+        outputs:
+            restricted_access: ${{ steps.permission.outputs.restricted_access }}
+        steps:
+            - id: permission
+              run: |
+                # Check if user is allowed to run priviledge workflows
+                restricted_acccess = ${{ github.event.pull_request.head.repo.fork }}
+                actor = ${{ github.triggering_actor }}
+                allowed_list=("touma-I" "revit13" "roytman")
+                for user in "${allowed_list[@]}"; do
+                    if [ "$user" ==  "$actor" ]; then
+                        restricted_access=false
+                        break
+                    fi
+                done
+                if $restricted_access; then
+                    # Explain and force-fail workflows
+                    echo "User $actor is not allowed to trigger this workflow."
+                    echo "$actor is not in list: ${allowed_list[*]} "
+                    exit 1
+                fi
+
     test-src:
+        needs: [check_if_allowed]
         runs-on: ubuntu-22.04
         env:
             HF_READ_ACCESS_TOKEN: ${{ secrets.HF_READ_ACCESS_TOKEN }}
         steps:
             - name: Expose secret to trusted users working in a fork
+              if: needs.check_if_allowed.outputs.restricted_access == 'false'
               run: |
-                  echo "Checking actor- :  ${{ github.actor }}"
-                  echo "Checking Trigger_actor- :  ${{ github.triggering_actor }}"
-                  echo "Checking user.login- :  ${{ github.event.pull_request.user.login }}"
-                  echo "Checking access- PR head:  ${{ github.event.pull_request.head.sha }}"
-                  echo "Checking access- github ref:  ${{ github.ref }}"
-                  $PWD/scripts/check-restricted-access.sh ${{ github.triggering_actor }} ${{ github.event.pull_request.head.repo.fork }}
+                  echo "Checking actor:${{ github.actor }} Trigger_actor:${{ github.triggering_actor }} user.login=${{ github.event.pull_request.user.login }}"
+                  echo "Checking PR.head.sha:${{ github.event.pull_request.head.sha }} github.ref: ${{ github.ref }}"
 
             - name: Checkout
               uses: actions/checkout@v4
