Get list of authorized users from env variable
Signed-off-by: Maroun Touma <touma@us.ibm.com>

diff --git a/.github/workflows/test-language-gneissweb_classification.yml b/.github/workflows/test-language-gneissweb_classification.yml
--- a/.github/workflows/test-language-gneissweb_classification.yml
+++ b/.github/workflows/test-language-gneissweb_classification.yml
@@ -78,25 +78,38 @@ jobs:
         steps:
             - id: permission
               run: |
-                # Check if user is allowed to run priviledge workflows
-                echo "vars.PRIVILEGED_USERS: ${{ vars.PRIVILEGED_USERS }}"
-                echo "Checking permission"
+                echo "Check if user is allowed to run priviledge workflows"
                 restricted_acccess=${{ github.event.pull_request.head.repo.fork }}
-                actor=${{ github.triggering_actor }}
-                echo "$restricted_acccess  $actor"
-                allowed_list=("touma-I" "revit13" "roytman")
-                for user in "${allowed_list[@]}"; do
-                    if [ "$user" ==  "$actor" ]; then
+
+                if [[ "${{ vars.PRIVILEGED_USERS }}" == *+${{ github.triggering_actor }}+* ]]; then
                         restricted_access=false
-                        break
-                    fi
-                done
+                fi
+
                 if $restricted_access; then
-                    # Explain and force-fail workflows
-                    echo "User $actor is not allowed to trigger this workflow."
-                    echo "$actor is not in list: ${allowed_list[*]} "
+                    echo "User ${{ github.triggering_actor }} is not allowed to trigger this workflow."
+                    echo "Authorized users list: ${{ vars.PRIVILEGED_USERS }} "
                     exit 1
                 fi
+
+#                # Check if user is allowed to run priviledge workflows
+#                echo "vars.PRIVILEGED_USERS: ${{ vars.PRIVILEGED_USERS }}"
+#                echo "Checking permission"
+#                restricted_acccess=${{ github.event.pull_request.head.repo.fork }}
+#                actor=${{ github.triggering_actor }}
+#                echo "$restricted_acccess  $actor"
+#                allowed_list=("touma-I" "revit13" "roytman")
+#                for user in "${allowed_list[@]}"; do
+#                    if [ "$user" ==  "$actor" ]; then
+#                        restricted_access=false
+#                        break
+#                    fi
+#                done
+#                if $restricted_access; then
+#                    # Explain and force-fail workflows
+#                    echo "User $actor is not allowed to trigger this workflow."
+#                    echo "$actor is not in list: ${allowed_list[*]} "
+#                    exit 1
+#                fi
 
     test-src:
         needs: [check_if_allowed]
@@ -107,7 +120,6 @@ jobs:
             - name: Expose secret to trusted users working in a fork
               if: "!needs.check_if_allowed.outputs.restricted_access"
               run: |
-                  echo "${{ vars.PRIVILEGED_USERS }}"
                   echo "Checking actor:${{ github.actor }} Trigger_actor:${{ github.triggering_actor }} user.login=${{ github.event.pull_request.user.login }}"
                   echo "Checking PR.head.sha:${{ github.event.pull_request.head.sha }} github.ref: ${{ github.ref }}"
 
@@ -144,7 +156,6 @@ jobs:
             - name: Expose secret to trusted users working in a fork
               if: needs.check_if_allowed.outputs.restricted_access == false
               run: |
-                  echo "${{ vars.PRIVILEGED_USERS }}"
                   echo "Checking actor:${{ github.actor }} Trigger_actor:${{ github.triggering_actor }} user.login=${{ github.event.pull_request.user.login }}"
                   echo "Checking PR.head.sha:${{ github.event.pull_request.head.sha }} github.ref: ${{ github.ref }}"
 
